# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\app\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 601)
        MainWindow.setStatusTip("")
        MainWindow.setDocumentMode(False)
        self.mainArea = QtWidgets.QWidget(MainWindow)
        self.mainArea.setObjectName("mainArea")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainArea)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.brushes = QtWidgets.QVBoxLayout()
        self.brushes.setSpacing(0)
        self.brushes.setObjectName("brushes")
        self.dotButton = QtWidgets.QPushButton(self.mainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dotButton.sizePolicy().hasHeightForWidth())
        self.dotButton.setSizePolicy(sizePolicy)
        self.dotButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.dotButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dotButton.setStyleSheet("margin: 2px; padding: 10px")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/assets/dot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dotButton.setIcon(icon)
        self.dotButton.setIconSize(QtCore.QSize(32, 32))
        self.dotButton.setDefault(False)
        self.dotButton.setFlat(True)
        self.dotButton.setObjectName("dotButton")
        self.brushes.addWidget(self.dotButton)
        self.lineButton = QtWidgets.QPushButton(self.mainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineButton.sizePolicy().hasHeightForWidth())
        self.lineButton.setSizePolicy(sizePolicy)
        self.lineButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.lineButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lineButton.setStyleSheet("margin: 2px; padding: 10px")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/assets/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineButton.setIcon(icon1)
        self.lineButton.setIconSize(QtCore.QSize(32, 32))
        self.lineButton.setDefault(False)
        self.lineButton.setFlat(True)
        self.lineButton.setObjectName("lineButton")
        self.brushes.addWidget(self.lineButton)
        self.polylineButton = QtWidgets.QPushButton(self.mainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polylineButton.sizePolicy().hasHeightForWidth())
        self.polylineButton.setSizePolicy(sizePolicy)
        self.polylineButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.polylineButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.polylineButton.setStyleSheet("margin: 2px; padding: 10px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/assets/polyline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.polylineButton.setIcon(icon2)
        self.polylineButton.setIconSize(QtCore.QSize(32, 32))
        self.polylineButton.setDefault(False)
        self.polylineButton.setFlat(True)
        self.polylineButton.setObjectName("polylineButton")
        self.brushes.addWidget(self.polylineButton)
        self.circleButton = QtWidgets.QPushButton(self.mainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.circleButton.sizePolicy().hasHeightForWidth())
        self.circleButton.setSizePolicy(sizePolicy)
        self.circleButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.circleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.circleButton.setStyleSheet("margin: 2px; padding: 10px")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/assets/circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.circleButton.setIcon(icon3)
        self.circleButton.setIconSize(QtCore.QSize(32, 32))
        self.circleButton.setDefault(False)
        self.circleButton.setFlat(True)
        self.circleButton.setObjectName("circleButton")
        self.brushes.addWidget(self.circleButton)
        self.rectagleButton = QtWidgets.QPushButton(self.mainArea)
        self.rectagleButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rectagleButton.sizePolicy().hasHeightForWidth())
        self.rectagleButton.setSizePolicy(sizePolicy)
        self.rectagleButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.rectagleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rectagleButton.setStyleSheet("margin: 2px; padding: 10px")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/assets/rectangle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectagleButton.setIcon(icon4)
        self.rectagleButton.setIconSize(QtCore.QSize(32, 32))
        self.rectagleButton.setDefault(False)
        self.rectagleButton.setFlat(True)
        self.rectagleButton.setObjectName("rectagleButton")
        self.brushes.addWidget(self.rectagleButton)
        self.removeButton = QtWidgets.QPushButton(self.mainArea)
        self.removeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeButton.setStyleSheet("margin: 2px; padding: 10px")
        self.removeButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/assets/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.removeButton.setIcon(icon5)
        self.removeButton.setIconSize(QtCore.QSize(32, 32))
        self.removeButton.setFlat(True)
        self.removeButton.setObjectName("removeButton")
        self.brushes.addWidget(self.removeButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.brushes.addItem(spacerItem)
        self.colorButton = QtWidgets.QPushButton(self.mainArea)
        self.colorButton.setStyleSheet("background-color: rgb(0, 0, 0);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/assets/color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.colorButton.setIcon(icon6)
        self.colorButton.setFlat(False)
        self.colorButton.setObjectName("colorButton")
        self.brushes.addWidget(self.colorButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.brushes.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.brushes)
        self.canvasAndInput = QtWidgets.QVBoxLayout()
        self.canvasAndInput.setContentsMargins(0, -1, -1, -1)
        self.canvasAndInput.setObjectName("canvasAndInput")
        self.splitter = QtWidgets.QSplitter(self.mainArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName("splitter")
        self.canvasHolder = QtWidgets.QScrollArea(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasHolder.sizePolicy().hasHeightForWidth())
        self.canvasHolder.setSizePolicy(sizePolicy)
        self.canvasHolder.setMinimumSize(QtCore.QSize(0, 400))
        self.canvasHolder.setBaseSize(QtCore.QSize(0, 0))
        self.canvasHolder.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.canvasHolder.setStyleSheet("margin: 10px;")
        self.canvasHolder.setWidgetResizable(True)
        self.canvasHolder.setObjectName("canvasHolder")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1022, 378))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.canvasHolder.setWidget(self.scrollAreaWidgetContents)
        self.historyHolder = QtWidgets.QScrollArea(self.splitter)
        self.historyHolder.setMinimumSize(QtCore.QSize(0, 0))
        self.historyHolder.setAutoFillBackground(True)
        self.historyHolder.setStyleSheet("border: none;")
        self.historyHolder.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.historyHolder.setWidgetResizable(True)
        self.historyHolder.setObjectName("historyHolder")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1044, 137))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.history = QtWidgets.QTextBrowser(self.scrollAreaWidgetContents_2)
        self.history.setStyleSheet("border: 1px solid black;")
        self.history.setObjectName("history")
        self.verticalLayout.addWidget(self.history)
        self.manualInput = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.manualInput.setStyleSheet("border: 1px solid black;")
        self.manualInput.setObjectName("manualInput")
        self.verticalLayout.addWidget(self.manualInput)
        self.historyHolder.setWidget(self.scrollAreaWidgetContents_2)
        self.canvasAndInput.addWidget(self.splitter)
        self.horizontalLayout.addLayout(self.canvasAndInput)
        MainWindow.setCentralWidget(self.mainArea)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setObjectName("actionLine")
        self.actionRectangle = QtWidgets.QAction(MainWindow)
        self.actionRectangle.setObjectName("actionRectangle")
        self.actionCircle = QtWidgets.QAction(MainWindow)
        self.actionCircle.setObjectName("actionCircle")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionManualInput = QtWidgets.QAction(MainWindow)
        self.actionManualInput.setObjectName("actionManualInput")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionQuit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OOP CAD"))
        self.rectagleButton.setWhatsThis(_translate("MainWindow", "Rectangle"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.actionNew.setText(_translate("MainWindow", "&New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("MainWindow", "&Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+W"))
        self.actionLine.setText(_translate("MainWindow", "Line"))
        self.actionRectangle.setText(_translate("MainWindow", "Rectangle"))
        self.actionCircle.setText(_translate("MainWindow", "Circle"))
        self.actionUndo.setText(_translate("MainWindow", "&Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "&Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Shift+Z"))
        self.actionSave.setText(_translate("MainWindow", "&Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionManualInput.setText(_translate("MainWindow", "ManualInput"))
        self.actionManualInput.setToolTip(_translate("MainWindow", "Manual Input"))

import app.ui.resources
